print ("hello world")
print ("hello world1")
print ("new FW rule")
print ("new FW rule1")
print ("new FW rule2")
print ("new FW rule3")
print ("new FW rule4")
print ("new FW rule5")
print ("WAF rule1")
print ("WAF rule2")
print ("WAF rule3")